package ru.stqa.pft.adressbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class ContactCreationTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost/addressbook/");
    login("admin", "secret");
  }

  private void login(String user, String password) {
    driver.manage().window().setSize(new Dimension(1158, 729));
    driver.findElement(By.name("user")).sendKeys(user);
    driver.findElement(By.name("pass")).sendKeys(password);
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactrCreationTests() {

    initNewContact();
    fillNewContact();
    submitNewContact();
  }

  private void submitNewContact() {
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void fillNewContact() {
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("Jan");
    driver.findElement(By.name("middlename")).sendKeys("Marian");
    driver.findElement(By.name("lastname")).sendKeys("Kowalski");
    driver.findElement(By.name("nickname")).sendKeys("Dominator");
    driver.findElement(By.name("company")).sendKeys("Opel");
    driver.findElement(By.name("address")).sendKeys("Kościuszki 220");
    driver.findElement(By.name("mobile")).click();
    driver.findElement(By.name("mobile")).sendKeys("512-22-222");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("jan@po.pl");
    driver.findElement(By.name("notes")).click();
    driver.findElement(By.name("notes")).sendKeys("Będzie dobrze!");
  }

  private void initNewContact() {
    driver.findElement(By.linkText("nowy wpis")).click();
  }
}
