package ru.stqa.pft.adressbook;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import ru.stqa.pft.adressbook.tests.TestBase;

import java.util.*;

public class ContactCreationTests extends TestBase {

  @Test
  public void contactrCreationTests() {

    initNewContact();
    fillNewContact(new ContactData("Jan", "Marian", "Kowalski", "Dominator", "Opel", "Kościuszki 220", "512-22-222", "jan@po.pl", "Będzie dobrze!"));
    submitNewContact();
  }

}
