package ru.stqa.pft.adressbook;// Generated by Selenium IDE

import org.junit.Test;
import ru.stqa.pft.adressbook.tests.TestBase;

public class ContactDeletionTests extends TestBase {

  @Test
  public void contactDeletionTests() {
    app.goToHomePage();
    app.selectAllContact();
    app.deleteSelectedContact();
  }

}
