package ru.stqa.pft.adressbook;// Generated by Selenium IDE
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import ru.stqa.pft.adressbook.tests.TestBase;

public class ContactCreationTests extends TestBase {

  @Test
  public void contactrCreationTests() {

    app.initNewContact();
    app.fillNewContact(new ContactData("Jan", "Marian", "Kowalski", "Dominator", "Opel", "Kościuszki 220", "512-22-222", "jan@po.pl", "Będzie dobrze!"));
    app.submitNewContact();
  }

}
