package ru.stqa.pft.adressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class ContactDeletionTests extends TestBase {

  @Test
  public void contactDeletionTests() {
    //app.getNavigationHelper().goToHomePage();
    app.getContactHelper().selectAllContact();
    app.getContactHelper().deleteSelectedContact();
  }

}
