package ru.stqa.pft.adressbook.tests;// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import ru.stqa.pft.adressbook.model.GroupData;

import java.util.Map;

public class GroupDeletionTests extends TestBase {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;


  @Test
  public void groupDeletionTests() {
    app.getNavigationHelper().gotoGroupPage();
    int before = app.getGroupHelper().getGroupCount();
    if (!app.getGroupHelper().isThereAGroup()) {
      app.getGroupHelper().createGroup(new GroupData("test1", null, null));

    }
    app.getGroupHelper().selectGroup(before - 1);
    app.getGroupHelper().deleteSelectedGroup();
    app.getGroupHelper().returnToGroupPage();
    int after = app.getGroupHelper().getGroupCount();
    Assert.assertEquals(after, before - 1);
  }

}
